### ISSUE TITLE
Some entities not working after upgrade

### ISSUE THREAD

**Issue by melaqu** [h4de5/home-assistant-vimar#38]
After the upgrade of HA os and core all vimar sensors are not available, this is my log:
![FAEA0101-6CA3-4733-BCA6-EEC0490D3064](https://user-images.githubusercontent.com/73409827/128377391-0aaeac46-8a06-4e0f-ba2f-33378cdcdec1.png)

Logger: homeassistant.setup
Source: setup.py:311 
First occurred: 16:58:24 (1 occurrences) 
Last logged: 16:58:24

Unable to prepare setup for platform vimar.sensor: Platform not found (cannot import name 'VOLT' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

Thanks in advance for your help!

**Comment by Niki206cc** [comment]
Hi i have the same issue....

**Comment by melaqu** [comment]
> Hi i have the same issue....

Ho provato a seguire questa guida (https://github.com/h4de5/home-assistant-vimar/issues/15#issuecomment-665635305 ) ma non ha funzionato, non vede completamente le entità sensore. Ho ripristinato l’istantanea 2021.7.4 e funziona tutto quindi il problema non è del sistema operativo. Tu hai trovato qualche soluzione?

**Comment by Niki206cc** [comment]
Ciao, no al momento non ancora....anche io ripristinando ho tutto funzionante.

**Comment by felisida** [comment]
see to, I have te same issue

**Comment by Niki206cc** [comment]
Solved, just copy and paste the new sensor.py in your folder and it works, as always h4de5 GREAT JOB!!!

**Comment by melaqu** [comment]
Yesss! Thanks again h4de5

**Comment by h4de5** [comment]
sorry. i should have commented here. the issue is fixed, as said with the new sensor.py. i'll create a new release today.

**Comment by felisida** [comment]
thanks a lot, do you have any idea why the new HA energy control function does not recognise vimar sensors for energy controll of consumed, fed in and produced?
![Schermata 2021-08-09 alle 11 13 54](https://user-images.githubusercontent.com/51525150/128684597-32a4cf89-2390-4ad0-ab9a-55ba317d993f.jpg)

**Comment by Niki206cc** [comment]
I have the same issue. I'm trying to add my SolarEdge sensor without succes but if it will be possible to add Vima sensor for me is better.

**Comment by h4de5** [comment]
I am not sure whats the issue here. as far as i had read through that concepts, you should get an energy sensor, for every `energia` status in your project. Please understand that if you only have an current (`fase` status) or any other status having "Watts" as unit, you will not be able you to use the energy module from HA.
in this case you may be able to create a new sensor and calculate the used/produced energy by [using the "integrale integration"](https://www.home-assistant.io/docs/energy/faq/#creating-an-energy-sensor-out-of-a-power-sensor)
