### ISSUE TITLE
Error during setup of component vimar

### ISSUE THREAD

**Issue by tlender** [h4de5/home-assistant-vimar#45]
Hello, I have problems to install vimar on the home-assistent.

my Setup:
- Environment: Synology DS1815+ 
- Home-Assistant Version: 2022.6.6 OS-Version in Synology VMM
- By-me web server Version: 2.10 (Rev. 25118)

- [ yes] the source code of the integration is cloned into the right directory: `config/custom_components/vimar`
- [ yes] the `config/` directory above (can be named differently) but it should hold the general `configuration.yaml` and the `home-assistant.log` file

My Problem:
![image](https://user-images.githubusercontent.com/107491893/174195879-c7a957e0-c041-4394-bf2f-2c815be99fbe.png)
![image](https://user-images.githubusercontent.com/107491893/174195958-879eec53-3807-4dd2-9537-426d9dbc73d0.png)

My configuration:
![image](https://user-images.githubusercontent.com/107491893/174195992-569ebeac-9951-4488-8239-700f42ee0602.png)
![image](https://user-images.githubusercontent.com/107491893/174196088-799d9c9d-62e4-4cdb-8f36-91d94cb16bf2.png)
![image](https://user-images.githubusercontent.com/107491893/174196136-9a34975a-7aa3-4daf-97c3-a83980370e51.png)

Please give me an reply, what i have to do.

Thomas

**Comment by h4de5** [comment]
Hallo Thomas,

try removing the certificate name from your configuration.

so either:
```
  ...
  host: xxxx
  certificate: 
```

or remove certificate completely

**Comment by tlender** [comment]
@h4de5 - Andi: Thanks for reply. But ist doesn´t work. I have removed the certification-line. But I got this logs:

<img width="1701" alt="image" src="https://user-images.githubusercontent.com/107491893/174255483-b234c33c-a35e-4e7e-801b-2248304ac5e9.png">

**Comment by h4de5** [comment]
it tries to login but the communication to the vimar webserverv cannot be established - possible due to an invalid certificate.

it says "certificate has expired" in your screenshots.

you can download the certificate manually from your vimar webserver: http://YOUR-HOST/vimarbyweb/modules/vimar-byme/script/rootCA.VIMAR.crt

check if that is really outdated. possible you need to regenerate the certificate on your webserver (i think it happens when you define a public host)

**Comment by tlender** [comment]
Hello, now it works, thank you!

But I have another Question because the blinds.
https://community.home-assistant.io/t/vimar-by-me-by-web-integration/202073/172?u=tlender

**Comment by kubaceg** [comment]
Hi, since few days I have same error, homeassistant can't log in into vimar. I've update certificate and check login everything is ok. I try with empty certificate config toom nothing works.

My error:
```(Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:997)')))```

When I get into browser I have such information about vimar certificate:
![Zrzut ekranu z 2022-07-08 11-24-49](https://user-images.githubusercontent.com/696884/177963675-5e426768-d673-4732-9808-1bceb5c6cbc8.png)

My web server has latest software version.

**Comment by h4de5** [comment]
mmh. did you update HA recently? maybe they updated some ssl library, that no longer trust, that given cypher. it seems the certificate provided from vimar is finally outdated due to it old cipher usage. unless vimar provides a new certificate, i we are out of luck.
for me only firefox works with the vimar webserverv directly.

**Comment by kubaceg** [comment]
Yep i have home assistant up to date. I suspect same reasons, for me web works only on ff too. I'll try write to vimar help desk and I hope there handle this certificate. If they dont i'm affraid that i have to search for some knx-ip solution :(

**Comment by kubaceg** [comment]
it turned out that I have old firmware on my webserver (I have 2.10 version which is is lower version than latest 2.3 🤣 ), so I make an update and now my webserver doesn't work totally (I must contact with technical support again). Nevertheless upgrade should fix certificates :)

**Comment by WhiteWolf84** [comment]
I have noticed it already. Vimar sucks. I've wrote to them about the
problem. They have similar issue with the alarm remote administration.
They ignored my warinigs.

Il ven 8 lug 2022, 18:02 Andi ***@***.***> ha scritto:
