### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'coroutine'

### ISSUE THREAD

**Issue by killerjem** [h4de5/home-assistant-vimar#63]
Hi, after upgrading from HA v2023.4.4 to HA v2023.6.0. I get this error message. In the integrations Vimar Byme HUB is not loaded.

Thanks

Logger: homeassistant.loader
Source: custom_components/vimar/__init__.py:64 
Integration: VIMAR By-Me Hub (documentation, issues) 
First occurred: 09:45:25 (1 occurrences) 
Last logged: 09:45:25

Unexpected exception importing component custom_components.vimar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/vimar/__init__.py", line 64, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

**Comment by WhiteWolf84** [comment]
Hi,
I've the same problem.

**Comment by h4de5** [comment]
this happens due to python 3.11 upgrade.
fix is under way

but.. it seems, at least my webserver uses a too old ssl cipher and the newer python library can no longer communicate with it:

> Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1002)')

I have no idea how to fix it, as the regular vimar webserver refuses to let me enter the configuration mode where i could update its firmware. 
does anybody know if there are other ways to update the vimar webserver?

**Comment by h4de5** [comment]
leaving it open in hope for others to see

**Comment by WhiteWolf84** [comment]
> this happens due to python 3.11 upgrade. fix is under way
> 
> but.. it seems, at least my webserver uses a too old ssl cipher and the newer python library can no longer communicate with it:
> 
> > Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1002)')
> 
> I have no idea how to fix it, as the regular vimar webserver refuses to let me enter the configuration mode where i could update its firmware. does anybody know if there are other ways to update the vimar webserver?

I don't use the configuration mode. I'm using chrome to access the setup menú in the gears bottom right (with Firefox you can't seee the link is inhibited)
Here you can update the new firmware in the setup - > update section

**Comment by h4de5** [comment]
I didn't update my webservers certificate - so at some point no other browser would let me open the web page due to this cypher mismatch. only in firefox I could allow that old certificate and login - but, as you just wrote - the webpage inhibit the use of firefox, so there was no general settings for me. I thought the webserver was broken or something .. 

all I needed to do was, change the user agent of firefox (see: https://www.whatismybrowser.com/guides/how-to-change-your-user-agent/firefox) to mimic the one from chrome - and I can finally go into the webservers settings again. 
THANK YOU. i was short before reseting everything and starting from scratch..

**Comment by killerjem** [comment]
thanks!!! now everything seems to work

**Comment by h4de5** [comment]
seems i just bricked my webserver. during the update it said, it has not enough space left and restarted. now not even a hard reset seems to work. it does not longer respond.

**Comment by WhiteWolf84** [comment]
Hi,

the webserver exposes various service such as  FTP. You can reach it via FTP? I don't know how to fix a bricked webserver but maybe Vimar support does. If you can reach it via FTP maybe can be some hope.

**Comment by h4de5** [comment]
nope, can not even ping it :/
